const PDFDocument = require('pdfkit');
const { Patient, Vitals, RiskLog } = require('../models');

exports.generateReport = async (req, res, next) => {
  try {
    const { patientId } = req.params;
    const patient = await Patient.findOne({ where: { patient_id: patientId } });
    if (!patient) return res.status(404).json({ success: false, message: 'Patient not found' });

    const vitals = await Vitals.findAll({
      where: { patient_id: patientId },
      order: [['timestamp', 'DESC']],
      limit: 20,
    });
    const riskLogs = await RiskLog.findAll({
      where: { patient_id: patientId },
      order: [['timestamp', 'DESC']],
      limit: 10,
    });

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=MedChain_Report_${patientId}.pdf`);
    doc.pipe(res);

    // Header
    doc.fontSize(24).fillColor('#1e40af').text('MedChain AI', { align: 'center' });
    doc.fontSize(10).fillColor('#64748b').text('AI-Powered Healthcare Monitoring Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown();

    // Patient Info
    doc.fontSize(16).fillColor('#0f172a').text('Patient Information');
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('#334155');
    doc.text(`Name: ${patient.name}`);
    doc.text(`Patient ID: ${patient.patient_id}`);
    doc.text(`Email: ${patient.email || 'N/A'}`);
    doc.text(`Age: ${patient.age || 'N/A'}`);
    doc.text(`Medical History: ${patient.medical_history || 'None recorded'}`);
    doc.text(`Report Generated: ${new Date().toLocaleString()}`);
    doc.moveDown();

    // Vitals History
    doc.fontSize(16).fillColor('#0f172a').text('Recent Vital Signs');
    doc.moveDown(0.3);

    if (vitals.length > 0) {
      // Table header
      const headers = ['Date', 'HR (bpm)', 'SpO2 (%)', 'Temp (°C)', 'BP (mmHg)'];
      const colW = [120, 80, 80, 80, 100];
      let x = 50;
      doc.fontSize(9).fillColor('#ffffff');
      doc.rect(50, doc.y, 460, 18).fill('#334155');
      const headerY = doc.y + 4;
      headers.forEach((h, i) => { doc.fillColor('#ffffff').text(h, x, headerY, { width: colW[i], align: 'center' }); x += colW[i]; });
      doc.y = headerY + 18;

      // Table rows
      vitals.slice(0, 10).forEach((v, idx) => {
        x = 50;
        const rowY = doc.y + 2;
        if (idx % 2 === 0) doc.rect(50, rowY - 2, 460, 16).fill('#f8fafc');
        doc.fillColor('#334155').fontSize(8);
        const vals = [
          new Date(v.timestamp).toLocaleDateString(),
          `${v.heart_rate}`, `${v.spo2}`, `${v.temperature}`,
          v.blood_pressure_systolic ? `${v.blood_pressure_systolic}/${v.blood_pressure_diastolic || '—'}` : 'N/A',
        ];
        vals.forEach((val, i) => { doc.text(val, x, rowY, { width: colW[i], align: 'center' }); x += colW[i]; });
        doc.y = rowY + 16;
      });
    } else {
      doc.fontSize(10).fillColor('#94a3b8').text('No vitals recorded yet.');
    }
    doc.moveDown();

    // Risk Assessment History
    doc.fontSize(16).fillColor('#0f172a').text('Risk Assessment History');
    doc.moveDown(0.3);

    const riskColors = { LOW: '#22c55e', MEDIUM: '#eab308', HIGH: '#f97316', CRITICAL: '#ef4444' };
    riskLogs.forEach((log) => {
      doc.fontSize(10).fillColor(riskColors[log.risk_level] || '#6b7280')
        .text(`[${log.risk_level}] ${new Date(log.timestamp).toLocaleString()}`);
      doc.fontSize(9).fillColor('#475569').text(`Reason: ${log.reason}`);
      doc.fontSize(9).fillColor('#475569').text(`Action: ${log.recommended_action}`);
      doc.moveDown(0.4);
    });

    if (riskLogs.length === 0) {
      doc.fontSize(10).fillColor('#94a3b8').text('No risk assessments recorded yet.');
    }

    // Footer
    doc.moveDown(2);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(0.5);
    doc.fontSize(8).fillColor('#94a3b8').text('This report was generated by MedChain AI. All health records are secured on blockchain.', { align: 'center' });
    doc.text('For medical decisions, please consult your healthcare provider.', { align: 'center' });

    doc.end();
  } catch (error) { next(error); }
};
